from summa import keywords
from summa.summarizer import summarize
text = "Neo-Nazism consists of post-World War II militant social or political movements seeking to revive and implement the ideology of Nazism. Neo-Nazis seek to employ their ideology to promote hatred and attack minorities, or in some cases to create a fascist political state. It is a global phenomenon, with organizedrepresentation in many countries and international networks. It borrows elementsfrom Nazi doctrine, including ultranationalism, racism, xenophobia, ableism, homophobia, anti-Romanyism, antisemitism, anti-communism and initiating the FourthReich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration of Adolf Hitler. In some European and Latin American countries, laws prohibit the expression of pro-Nazi, racist, anti-Semitic, or homophobic views. Many Nazi-related symbols are banned in European countries (especiallyGermany) in an effort to curtail neo-Nazism. The term neo-Nazism describes any post-World War II militant, social or political movements seeking to revive the ideology of Nazism in whole or in part. The term neo-Nazism can also refer to theideology of these movements, which may borrow elements from Nazi doctrine, including ultranationalism, anti-communism, racism, ableism, xenophobia, homophobia,anti-Romanyism, antisemitism, up to initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration ofAdolf Hitler. Neo-Nazism is considered a particular form of far-right politics and right-wing extremism."
text2 = "Moments prior to Naruto Uzumaki's birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the Fourth Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. Now, Naruto is a hyperactive and knuckle-headed ninja still living in Konohagakure. Shunned because of the Kyuubi inside him, Naruto struggles to find his place in the village, while his burning desire to become the Hokage of Konohagakure leads him not only to some great new friends, but also some deadly foes. [Written by MAL Rewrite]"
text3 = "Medieteknikdagen är en arbetsmarknadsdag för medieteknikprogrammet på Linköpings universitet. Ännu ett år förenar vi hundratals studenter och företag i industrin. Här hittar du all information och alla kontaktuppgifter du kan tänkas behöva Mässan kommer att hållas på campus Norrköping, Bredgatan 33. Här kan företag och studenter träffas och binda kontakt med varandra Som student får du den perfekta chansen att träffa tidigare studenter tillsammans med företag och prata och diskutera. Medieteknikdagen är till för att föra studenter och företag samman. Det är en mycket uppskattad mässa från både studenter och företag. Nedan kan du se hur det har sett ut tidigare år under MTD"
# Define length of the summary as a proportion of the text

print(summarize(text3, ratio=0.2))

summarize(text3, words=50)
print("\nKeywords:\n", keywords.keywords(text3))
# to print the top 3 keywords
print("Top 3 Keywords:\n", keywords.keywords(text3, words=3))
